# Site settings
title: ahuigo
name: ahuigo
email: 
description: ''
baseurl: ""
url: "http://ahuigo.github.io"
username: ahuigo 

# Build settings
exclude: ['posts1']
markdown: kramdown
paginate: 10 
paginate_path: "/p:num"
permalink: /p/:title
